install-guest:
	yes | chmod 755 ./vmware-mount-shared.sh
	yes | sudo sh ./install-tools.sh

mount-shared-first:
	yes | sudo sh ./vmware-mount-shared-first.sh

mount-shared:
	yes | sudo sh ./vmware-mount-shared.sh
