git-clean-get:
	cd .. && make git-clean-get

update:
	cd .. && make update

ins-mwheel:
	cd .. && make ins-mwheel

fix-mwheel:
	cd .. && make fix-mwheel

ins-devenv:
	cd .. && make ins-devenv

ins-devenv-ubuntu:
	cd .. && make ins-devenv-ubuntu

ins-scoop:
	cd .. && make ins-scoop

fix-pip:
	cd .. && make fix-pip

ins-golang:
	cd .. && make ins-golang

ins-golang-snap:
	sudo snap install go
	echo "https://stackoverflow.com/a/57434744"
	echo "sudo vim /etc/environment"
	echo "append :/snap/bin"
	echo "sudo reboot"

ins-clask-vlc:
	cd .. && make ins-clask-vlc

ins-ps:
	cd .. && make ins-ps

ins-docker:
	cd .. && make ins-docker

ins-brew:
	cd .. && make ins-brew

fix-brew:
	cd .. && make fix-brew

ins-git:
	cd .. && make ins-git

ins-wget:
	cd .. && make ins-wget

ins-curl:
	cd .. && make ins-curl

ins-vscode:
	cd .. && make ins-vscode

ins-chrome:
	cd .. && make ins-chrome

install-ssh-pass-linux:
	cd .. && make install-ssh-pass-linux

ins-li-fonts:
	cd .. && make ins-li-fonts

ins-cent-fonts:
	cd .. && make ins-cent-fonts

ins-cent-build:
	cd .. && make ins-cent-build

ins-li-build:
	cd .. && make ins-li-build

ins-li-ozsh:
	cd .. && make ins-li-build

ins-cent-ozsh:
	cd .. && make ins-cent-ozsh

ins-li-ch-zsh:
	cd .. && make ins-li-ch-zsh

ins-vmguest:
	cd .. && make ins-vmguest

vm-mount-script-copy:
	cd .. && make vm-mount-script-copy

vm-mount-shared:
	cd .. && make vm-mount-shared
